### ISSUE TITLE
TypeError: self_1.items.findIndex is not a function

### ISSUE THREAD

**Issue by OPADA-Eng** [moayadnajd/nativescript-comments#5]
Hi,
I'm using the plugin with ObservableArray but when I press "like" button I get an error as shown:

 

> An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onTouch failed
>TypeError: self_1.items.findIndex is not a function

**Comment by moayadnajd** [comment]
i just add ObservableArray support thanks
