### ISSUE TITLE
Not exists class name in template

### ISSUE THREAD

**Issue by whins** [moayadnajd/nativescript-comments#9]
Hi 
I think need add class **comment-text** to comment template 

`<Label row="1" col="1" text="{{ comment }}" class="comment-text" textWrap="true" />`

Please check it

**Comment by moayadnajd** [comment]
@whins thanks for mention this   please update to latest i just added what you ask for

**Comment by whins** [comment]
I'm sorry
@moayadnajd Please add same class at line #333

**Comment by moayadnajd** [comment]
@whins i did but i did not push i will see the nom

**Comment by moayadnajd** [comment]
@whins the npm has it so everything good now
